config:
  target: 'https://test.essentialneed.org'
  phases:
    - duration: 8
      arrivalRate: 50

scenarios:
  -
    name: "Browsing"
    flow:
      -
        get:
          url: "/"
      -
        think: 2
      -
        get:
          url: "/about-us"
      -
        think: 2
      -
        get:
          url: "/meet-our-team"
      -
        think: 2
      -
        get:
          url: "/login"
